### ISSUE TITLE
java.util.ConcurrentModificationException in Specs with loops

### ISSUE THREAD

**Issue by artem-zinnatullin** [spekframework/spek#169]
We have some Specs with loops that were working fine on Spek 1.0.25, they're not working with Spec 1.0.89 and above.

Such kinds of Specs are failing with `ConcurrentModificationException`:

```kotlin
LoopSpec : Spek({

    listOf(1, 2, 3).forEach {
      on("$it") {
        
        it("is equal to current i") {
          assertThat(i).isEqualTo(i)
        }
      }
   }
})
```

Full stacktrace with Spek 1.1.0-beta3 and `1.0.0-M3` junit-platform-engine with `@RunWith(JUnitPlatform::class)`:
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:86)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$0(HierarchicalTestExecutor.java:87)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:129)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:116)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


```

**Comment by raniejade** [comment]
`i` here is `it`, right? This works w and w/o `@RunWith(...)`.

```kotlin
object ObjectSampleSpec: Spek({
    listOf(1, 2, 3).forEach {
        on("$it") {

            it("is equal to current it") {
                assertThat(it, equalTo(it))
            }
        }
    }
})
```

Are you running tests in parallel?

**Comment by artem-zinnatullin** [comment]
Sorry for the delay, no, we're not running tests in parallel, indeed my example actually works while real-life test that used to work on Spek 1.0.25 now fails 100% of the time, I'll try to dive deeper and get back with reproducible test case.

**Comment by raniejade** [comment]
It would be great If you could give a spec that reproduces the exception. I kinda have an idea how the exception might happen.

**Comment by AntonRutkevich** [comment]
BTW, just got the same issue migrating to

`
org.jetbrains.spek:spek-api:1.1.0-beta4
org.junit.platform:junit-platform-runner:1.0.0-M3
`

from 1.0.89 + M2, which works fine
`
org.jetbrains.spek:spek-api:1.0.89
org.junit.platform:junit-platform-runner:1.0.0-M2
`
