### ISSUE TITLE
Spec without default constructor should be ignored

### ISSUE THREAD

**Issue by robstoll** [spekframework/spek#200]
I am using the following pattern: 
- Write a Spec for an interface. 
- This Spec requires a factory method as parameter of the constructor (in order to create the concrete implementation)
- I am reusing this spec in the module where I am implementing the interface

Everything works fine if I run it with gradle. Yet, if I try to run it in intellij I get the following error:
````
INFO: Discovered TestEngines with IDs: [spek]
Exception in thread "main" java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.jetbrains.spek.engine.SpekTestEngine$defaultInstanceFactory$1.create(SpekTestEngine.kt:231)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:113)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:74)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:109)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
````
The problem is in `SpekEngineTest::instanceFactoryFor` should not use `defaultInstanceFactory` in case `spek` does not have a default constructor.

**Comment by robstoll** [comment]
Oh well... setting the Spec abstract works as well :)
I do not close the issue on purpose though. IMO it shouldn't fail. Or if it fails it should print out the suggestion that the Spec should be made `abstract`. That would surely be more user friendly

**Comment by raniejade** [comment]
> Edit: I even have a use case where I cannot make it abstract, because I want to use it in an include

I think we could introduce an `@IgnoreSpek` annotation to ignore non-abstract classes.

**Comment by robstoll** [comment]
Sounds like a plan

**Comment by raniejade** [comment]
Closing this as `2,x` introduced `@Ignore`.
