### ISSUE TITLE
Memoized usage in test names results in exception

### ISSUE THREAD

**Issue by arturdryomov** [spekframework/spek#211]
```kotlin
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.context
import org.jetbrains.spek.api.dsl.it
import org.junit.platform.runner.JUnitPlatform
import org.junit.runner.RunWith

@RunWith(JUnitPlatform::class)
class MemoizedSpec : Spek({

    val environment by memoized { Environment() }

    context("environment $environment") {

        it("does not work") {
        }
    }

}) {

    class Environment

}
```

This test results in such exception.

```
java.lang.NullPointerException
	at org.junit.platform.runner.JUnitPlatformRunnerListener.executionStarted(JUnitPlatformRunnerListener.java:62)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionStarted$2(TestExecutionListenerRegistry.java:72)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionStarted(TestExecutionListenerRegistry.java:72)
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionStarted(ExecutionListenerAdapter.java:46)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:74)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:132)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by ming13** [comment]
BTW it is possible that something is wrong with my toolchain, but when I rename `MemoizedSpec` to `Memoized` it passes...

**Comment by raniejade** [comment]
The name shouldn't matter, have you tried renaming it back again to `MemoizedSpec` to see if it works?

**Comment by ming13** [comment]
The naming probably is just a bad luck, but I’ve tried the code above on another computer just in case and it still results in the same crash.

**Comment by jreiter** [comment]
This happens for me whenever I combine Spek and PowerMock.  If I integrate PowerMock and Spek using the `PowerMockRunnerDelegate` (delegating to `JUnitPlatform`), the first test (alphabetically) in my suite that uses Spek, but not PowerMock, results in this exact same stacktrace.  However, all subsequent tests using Spek work fine.

Any ideas?

**Comment by raniejade** [comment]
@jreiter Sorry, I don't know why this is happening yet. Tried the previous example and it worked for me. It will be very helpful, if you can provide me with an example project that reproduces this.

**Comment by jreiter** [comment]
@raniejade Yep, I will try making a minimal project that can reproduce the error.  I'll post it here when I have it.

By the way, when I was searching around for solutions for integrating PowerMock with Spek, I stumbled across a Google Groups where you were discussing adding first class support for PowerMock in Spek.  Did that ever go anywhere?

**Comment by raniejade** [comment]
I wasn't able to work on it further, last thing I did was introduce `@CreateWith` to allow Spek to use PowerMock's custom classloader.
